import { ConfiguredSectNodePlugin, type SectBuildBuilder } from '../../../../core';
import { CONDEMNATION_BUILD_FACADE, type JiujieCondemnationBuildFacade } from '../../shared/buildFacade';
const node = (id: string, layerId: string, name: string, description: string, apply: (facade: JiujieCondemnationBuildFacade) => void) => new ConfiguredSectNodePlugin({ id, layerId, name, description }, (_context, builder: SectBuildBuilder) => apply(builder.requireExtension<JiujieCondemnationBuildFacade>(CONDEMNATION_BUILD_FACADE, '天谴加身构筑')));
export const JIUJIE_CONDEMNATION_NODES = [
  node('condemnation-record', '1', '记名', '劫雷持续时间延长1回合。', (f) => f.extendThunder()), node('condemnation-question', '1', '问行', '雷狱问行伤害系数提高0.15法攻。', (f) => f.strengthenQuestion()), node('condemnation-first-crime', '1', '初罪', '劫雷行动触发伤害系数提高0.02法攻。', (f) => f.strengthenThunderTrigger()),
  node('condemnation-repeat', '2', '重犯', '每层重犯的清算伤害系数提高0.10法攻。', (f) => f.strengthenReoffend()), node('condemnation-heavy-debt', '2', '重典', '每层劫债的清算伤害系数提高0.05法攻。', (f) => f.strengthenDebtSettlement()), node('condemnation-long-record', '2', '长录', '劫雷持续时间再次延长1回合。', (f) => f.extendThunder()),
  node('condemnation-no-pardon', '3', '不赦', '劫雷持续时间再次延长1回合。', (f) => f.extendThunder()), node('condemnation-debt-book', '3', '债簿', '每层劫债的清算伤害系数再次提高0.05法攻。', (f) => f.strengthenDebtSettlement()), node('condemnation-heaven-hearing', '3', '天听', '劫雷行动触发伤害系数再次提高0.02法攻。', (f) => f.strengthenThunderTrigger()),
  node('condemnation-heavy-statute', '4', '重法', '雷狱问行伤害系数再次提高0.15法攻。', (f) => f.strengthenQuestion()), node('condemnation-quick-record', '4', '疾书', '劫雷持续时间再次延长1回合。', (f) => f.extendThunder()), node('condemnation-three-questions', '4', '三问', '每层重犯的清算伤害系数再次提高0.10法攻。', (f) => f.strengthenReoffend()),
  node('condemnation-reoffend', '5', '再犯', '每层重犯的清算伤害系数再次提高0.10法攻。', (f) => f.strengthenReoffend()), node('condemnation-clear-book', '5', '清册', '九霄清算后延长劫雷1回合。', (f) => f.strengthenSettlement()), node('condemnation-no-escape', '5', '无逃', '劫雷持续时间再次延长1回合。', (f) => f.extendThunder()),
  node('condemnation-final-verdict', 'ultimate', '终审', '九霄清算后再次延长劫雷1回合。', (f) => f.strengthenSettlement()), node('condemnation-nine-crimes', 'ultimate', '九罪', '每层劫债的清算伤害系数再次提高0.05法攻。', (f) => f.strengthenDebtSettlement()), node('condemnation-heavenly-punishment', 'ultimate', '天谴', '九霄清算后再次延长劫雷1回合。', (f) => f.strengthenSettlement()),
] as const;
